// @ts-check
import eslint from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist*/**",
      "**/*.min.js",
      "extension/dist*/**",
      ".worktrees/**",
      ".venv/**",
      "**/.venv/**",
      // Emitted artifacts (tsc/esbuild output, git-ignored)
      "extension/popup/*.js",
      "src/openbiliclaw/web/**/*.js",
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{js,mjs,ts}"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        fetch: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        chrome: "readonly",
        browser: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        HTMLElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLButtonElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLTextAreaElement: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        EventSource: "readonly",
        WebSocket: "readonly",
        FormData: "readonly",
        AbortController: "readonly",
        requestAnimationFrame: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        Image: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        btoa: "readonly",
        atob: "readonly",
        crypto: "readonly",
        indexedDB: "readonly",
        queueMicrotask: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        performance: "readonly",
      },
    },
    rules: {
      // Permissive start: legacy code triggers these; warn-only until follow-up F7/F8.
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "warn",
      "no-unused-vars": "off",
      "no-empty": "warn",
      "no-constant-condition": "warn",
      "no-useless-escape": "warn",
      "no-prototype-builtins": "warn",
      "@typescript-eslint/no-unused-expressions": "warn",
      "no-fallthrough": "warn",
      "no-case-declarations": "off",
      "prefer-const": "warn",
      "no-var": "warn",
      "no-redeclare": "warn",
      "no-regex-spaces": "warn",
      "@typescript-eslint/no-unsafe-function-type": "warn",
      "no-dupe-keys": "warn",
      "no-unreachable": "warn",
      "no-self-assign": "warn",
      "no-useless-catch": "warn",
      "no-misleading-character-class": "warn",
      "@typescript-eslint/no-this-alias": "warn",
      "@typescript-eslint/no-require-imports": "off",
      "no-undef": "off",
    },
  },
  {
    files: ["**/*.mjs", "scripts/**/*.mjs", "extension/scripts/**/*.mjs", "tests/**/*.mjs"],
    languageOptions: {
      globals: {
        process: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        Buffer: "readonly",
        global: "readonly",
        module: "readonly",
        require: "readonly",
      },
    },
  },
);
