"""API route contract regression test.

Locks the externally visible FastAPI routing surface so the incremental
``api/app.py`` extraction (Phase 1 of the architecture refactor) cannot
change route order, methods, names, WebSocket/Mount coverage, or OpenAPI
operation shapes without an explicit contract update.

The manifest is generated by ``scripts/generate_api_route_contract.py`` and
checked in at ``tests/contracts/api-route-contract.json``. To regenerate
after an intentional route change::

    python scripts/generate_api_route_contract.py > tests/contracts/api-route-contract.json

then review the diff carefully (route order and names matter).
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

from openbiliclaw.api.app import create_app

# Load the generator by file path (scripts/ is not an installed package).
_GENERATOR_PATH = (
    Path(__file__).resolve().parent.parent / "scripts" / "generate_api_route_contract.py"
)
_spec = importlib.util.spec_from_file_location("generate_api_route_contract", _GENERATOR_PATH)
assert _spec is not None and _spec.loader is not None
_gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_gen)
build_manifest = _gen.build_manifest

CONTRACT_PATH = Path(__file__).parent / "contracts" / "api-route-contract.json"


@pytest.fixture(scope="module")
def checked_in_contract() -> dict:
    with CONTRACT_PATH.open("r", encoding="utf-8") as fh:
        return json.load(fh)


@pytest.fixture(scope="module")
def live_manifest() -> dict:
    app = create_app()
    return build_manifest(app)


def test_app_routes_match_contract(checked_in_contract: dict, live_manifest: dict) -> None:
    """The ordered ``app.routes`` metadata (incl. WS/Mount) is unchanged."""
    expected = checked_in_contract["app_routes"]
    actual = live_manifest["app_routes"]
    assert actual == expected, (
        "app.routes drift detected. If this is intentional, regenerate "
        "tests/contracts/api-route-contract.json with "
        "scripts/generate_api_route_contract.py and review the diff."
    )


def test_openapi_operations_match_contract(checked_in_contract: dict, live_manifest: dict) -> None:
    """The OpenAPI HTTP surface (paths, methods, operationIds, response shapes) is unchanged."""
    expected = checked_in_contract["openapi_operations"]
    actual = live_manifest["openapi_operations"]
    assert actual == expected, (
        "OpenAPI operations drift detected. If this is intentional, regenerate "
        "tests/contracts/api-route-contract.json with "
        "scripts/generate_api_route_contract.py and review the diff."
    )


def test_no_duplicate_route_registration(live_manifest: dict) -> None:
    """New + legacy copies of the same (path, method) must never be live together.

    HTTP duplicates are keyed by (path, method). WebSocket routes and Mount
    entries carry no method list in the manifest, so they are keyed by
    (path, kind) instead — a duplicate WS path or a duplicate Mount path is
    just as much of a registration bug as a duplicate HTTP verb.
    """
    seen_http: set[tuple[str, str]] = set()
    seen_ws: set[str] = set()
    seen_mount: set[str] = set()
    for route in live_manifest["app_routes"]:
        path = route["path"]
        if route.get("is_websocket"):
            assert path not in seen_ws, f"duplicate websocket registration: {path}"
            seen_ws.add(path)
            continue
        if route.get("is_mount"):
            assert path not in seen_mount, f"duplicate mount registration: {path}"
            seen_mount.add(path)
            continue
        methods = route.get("methods") or []
        for method in methods:
            if method in {"HEAD", "OPTIONS"}:
                continue
            key = (path, method)
            assert key not in seen_http, f"duplicate route registration: {key}"
            seen_http.add(key)
