"""vnext baseline

Revision ID: 0001
Revises:
Create Date: 2026-07-17 01:13:31.560102
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_name", sa.String(length=100), nullable=False),
        sa.Column("model_alias", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("usage", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_runs")),
    )
    with op.batch_alter_table("ai_runs", schema=None) as batch_op:
        batch_op.create_index("ai_task_started", ["task_name", "started_at"], unique=False)

    op.create_table(
        "collections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collections")),
        sa.UniqueConstraint("slug", name=op.f("uq_collections_slug")),
    )
    collections_table = sa.table(
        "collections",
        sa.column("id", sa.String(length=36)),
        sa.column("slug", sa.String(length=50)),
        sa.column("display_name", sa.String(length=100)),
    )
    op.bulk_insert(
        collections_table,
        [
            {
                "id": "00000000-0000-0000-0000-000000000f01",
                "slug": "favorites",
                "display_name": "Favorites",
            },
            {
                "id": "00000000-0000-0000-0000-000000000f02",
                "slug": "watch_later",
                "display_name": "Watch later",
            },
        ],
    )
    op.create_table(
        "content_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=500), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("creator", sa.String(length=500), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("media_type", sa.String(length=50), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_items")),
        sa.UniqueConstraint("source_id", "external_id", name="content_identity"),
    )
    op.create_table(
        "job_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_name", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_runs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_job_runs_idempotency_key")),
    )
    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.create_index("job_status_created", ["status", "created_at"], unique=False)

    op.create_table(
        "profile_revisions",
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("narrative", sa.Text(), nullable=False),
        sa.Column("facets", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("profile_id", "revision", name=op.f("pk_profile_revisions")),
        sa.UniqueConstraint("revision", name="profile_revision_number"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "source_accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=50), nullable=False),
        sa.Column("account_key", sa.String(length=200), nullable=False),
        sa.Column("encrypted_credentials", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_accounts")),
        sa.UniqueConstraint("source_id", "account_key", name="source_account_identity"),
    )
    with op.batch_alter_table("source_accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_accounts_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "source_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=50), nullable=False),
        sa.Column("operation", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("request_payload", sa.JSON(), nullable=False),
        sa.Column("result_payload", sa.JSON(), nullable=True),
        sa.Column("lease_token", sa.String(length=100), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("request_deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_tasks")),
    )
    with op.batch_alter_table("source_tasks", schema=None) as batch_op:
        batch_op.create_index(
            "source_task_claim",
            ["source_id", "status", "request_deadline_at", "created_at"],
            unique=False,
        )

    op.create_table(
        "activity_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=50), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_external_id", sa.String(length=500), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=1000), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["source_accounts.id"],
            name=op.f("fk_activity_events_account_id_source_accounts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_events")),
    )
    with op.batch_alter_table("activity_events", schema=None) as batch_op:
        batch_op.create_index(
            "activity_source_occurred", ["source_id", "occurred_at"], unique=False
        )

    op.create_table(
        "candidate_assessments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("content_id", sa.String(length=36), nullable=False),
        sa.Column("profile_revision", sa.Integer(), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.Column("quality", sa.Float(), nullable=False),
        sa.Column("novelty", sa.Float(), nullable=False),
        sa.Column("risk", sa.Float(), nullable=False),
        sa.Column("topics", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content_items.id"],
            name=op.f("fk_candidate_assessments_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profile_revision"],
            ["profile_revisions.revision"],
            name=op.f("fk_candidate_assessments_profile_revision_profile_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_assessments")),
        sa.UniqueConstraint("content_id", "profile_revision", name="assessment_identity"),
    )
    with op.batch_alter_table("candidate_assessments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_assessments_content_id"), ["content_id"], unique=False
        )

    op.create_table(
        "chat_turns",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ai_run_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["ai_run_id"],
            ["ai_runs.id"],
            name=op.f("fk_chat_turns_ai_run_id_ai_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_turns")),
    )
    with op.batch_alter_table("chat_turns", schema=None) as batch_op:
        batch_op.create_index(
            "chat_conversation_created", ["conversation_id", "created_at"], unique=False
        )

    op.create_table(
        "collection_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column("content_id", sa.String(length=36), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_collection_items_collection_id_collections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content_items.id"],
            name=op.f("fk_collection_items_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection_items")),
        sa.UniqueConstraint("collection_id", "content_id", name="collection_content_identity"),
    )
    op.create_table(
        "interactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("content_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content_items.id"],
            name=op.f("fk_interactions_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interactions")),
    )
    with op.batch_alter_table("interactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_interactions_content_id"), ["content_id"], unique=False
        )

    op.create_table(
        "profile_evidence",
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("profile_revision", sa.Integer(), nullable=False),
        sa.Column("facet_name", sa.String(length=80), nullable=False),
        sa.Column("facet_value", sa.String(length=500), nullable=False),
        sa.Column("activity_event_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_event_id"],
            ["activity_events.id"],
            name=op.f("fk_profile_evidence_activity_event_id_activity_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id", "profile_revision"],
            ["profile_revisions.profile_id", "profile_revisions.revision"],
            name=op.f("fk_profile_evidence_profile_id_profile_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "profile_id",
            "profile_revision",
            "facet_name",
            "facet_value",
            "activity_event_id",
            name=op.f("pk_profile_evidence"),
        ),
    )
    op.create_table(
        "profile_consumed_evidence",
        sa.Column("activity_event_id", sa.String(length=36), nullable=False),
        sa.Column("profile_revision", sa.Integer(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_event_id"],
            ["activity_events.id"],
            name=op.f("fk_profile_consumed_evidence_activity_event_id_activity_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profile_revision"],
            ["profile_revisions.revision"],
            name=op.f("fk_profile_consumed_evidence_profile_revision_profile_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("activity_event_id", name=op.f("pk_profile_consumed_evidence")),
    )
    op.create_table(
        "feed_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("content_id", sa.String(length=36), nullable=False),
        sa.Column("assessment_id", sa.String(length=36), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("admitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["candidate_assessments.id"],
            name=op.f("fk_feed_entries_assessment_id_candidate_assessments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content_items.id"],
            name=op.f("fk_feed_entries_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feed_entries")),
    )
    with op.batch_alter_table("feed_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_feed_entries_content_id"), ["content_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_feed_entries_position"), ["position"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feed_entries_position"))
        batch_op.drop_index(batch_op.f("ix_feed_entries_content_id"))

    op.drop_table("feed_entries")
    op.drop_table("profile_consumed_evidence")
    op.drop_table("profile_evidence")
    with op.batch_alter_table("interactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interactions_content_id"))

    op.drop_table("interactions")
    op.drop_table("collection_items")
    with op.batch_alter_table("chat_turns", schema=None) as batch_op:
        batch_op.drop_index("chat_conversation_created")

    op.drop_table("chat_turns")
    with op.batch_alter_table("candidate_assessments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_assessments_content_id"))

    op.drop_table("candidate_assessments")
    with op.batch_alter_table("activity_events", schema=None) as batch_op:
        batch_op.drop_index("activity_source_occurred")

    op.drop_table("activity_events")
    with op.batch_alter_table("source_tasks", schema=None) as batch_op:
        batch_op.drop_index("source_task_claim")

    op.drop_table("source_tasks")
    with op.batch_alter_table("source_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_accounts_source_id"))

    op.drop_table("source_accounts")
    op.drop_table("settings")
    op.drop_table("profile_revisions")
    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.drop_index("job_status_created")

    op.drop_table("job_runs")
    op.drop_table("content_items")
    op.drop_table("collections")
    with op.batch_alter_table("ai_runs", schema=None) as batch_op:
        batch_op.drop_index("ai_task_started")

    op.drop_table("ai_runs")
    # ### end Alembic commands ###
